module.exports = {

    COMMUNITY_CHAT: "COMMUNITY_CHAT",
    LOGOUT: "LOGOUT",
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    MESSAGE_SENT: "MESSAGE_SENT",
    PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
    TYPING: "TYPING",
    USER_CONNECTED: "USER_CONNECTED",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    VERIFY_USER: "VERIFY_USER",

    ADD_USER: 'ADD_USER',
    ADD_MESSAGE: 'ADD_MESSAGE'

}
